### ISSUE TITLE
Typo3 13 version

### ISSUE THREAD

**Issue by gmt-it** [specialistaweb/textimage_size#4]
Hello.

Is a version for typo3 13 planned?

Best regards

Guido

**Comment by specialistaweb** [comment]
hi thank you, will be available today! So I close this issue...

**Comment by gmt-it** [comment]
Hi.
That would be great. I tested it with 13.4.1. Unfortunately it doesn't work. The Bootstrap package prevents the use of layout...

![image](https://github.com/user-attachments/assets/47fc68ed-32b6-472c-b723-3269dd4e8d8d)

**Comment by specialistaweb** [comment]
Hi on my test site and server the +ext works correctly under TYPO3 13 and bp 15

   check if you have included library from

   Edit whole Typoscript > Advanced options

   With a few minutes you will find the download file published here:

   https://extensions.typo3.org/extension/textimage_size

   at the moment avoid to use composer

   I wait for an answer.

   Alessandro Tuveri
   cell. +39 379 2306014
     _________________________________________________________________

   http://www.specialistaweb.it 
   Realizzazione e gestione di siti web di qualità, dinamici e professionali; portali per aziende, e-commerce, qualsiasi interazione; marketing e gestione social
   Giulia Tuveri - cell. +39 339 711 5662

   Da "gmt-it" ***@***.***
   A "specialistaweb/textimage_size" ***@***.***
   Cc "Alessandro Tuveri" ***@***.***,"Comment" ***@***.***
   Data Wed, 04 Dec 2024 01:29:41 -0800
   Oggetto Re: [specialistaweb/textimage_size] Typo3 13 version (Issue #4)

   Hi.
   That would be great. I tested it with 13.4.1. Unfortunately it doesn't work. The Bootstrap package prevents the use of layout...

   image.png (view on web)

**Comment by gmt-it** [comment]
Hello. 
Yes, I have integrated the library. I will download it again and test it. I will get back to you. But it will be around the afternoon.

**Comment by specialistaweb** [comment]
Hi I have installed v. 3.3.0 under TYPO3 13, all seemed to work correctly, but I reinstalled from repository and the Layout > Options are disappearer

   I hope to solve in brief, thank you for your suggestions

   Alessandro Tuveri
   cell. +39 379 2306014
     _________________________________________________________________

   http://www.specialistaweb.it 
   Realizzazione e gestione di siti web di qualità, dinamici e professionali; portali per aziende, e-commerce, qualsiasi interazione; marketing e gestione social
   Giulia Tuveri - cell. +39 339 711 5662

   Da "gmt-it" ***@***.***
   A "specialistaweb/textimage_size" ***@***.***
   Cc "Alessandro Tuveri" ***@***.***,"Comment" ***@***.***
   Data Wed, 04 Dec 2024 02:56:32 -0800
   Oggetto Re: [specialistaweb/textimage_size] Typo3 13 version (Issue #4)

   Hello.
   Yes, I have integrated the library. I will download it again and test it. I will get back to you. But it will be around the afternoon.

**Comment by specialistaweb** [comment]
Hi I need to modify/add some styles and move a file to restore the layout menu

   Please wait 1-2 days

   Alessandro Tuveri
   cell. +39 379 2306014
     _________________________________________________________________

   http://www.specialistaweb.it 
   Realizzazione e gestione di siti web di qualità, dinamici e professionali; portali per aziende, e-commerce, qualsiasi interazione; marketing e gestione social
   Giulia Tuveri - cell. +39 339 711 5662

   Da "gmt-it" ***@***.***
   A "specialistaweb/textimage_size" ***@***.***
   Cc "Alessandro Tuveri" ***@***.***,"Comment" ***@***.***
   Data Wed, 04 Dec 2024 02:56:32 -0800
   Oggetto Re: [specialistaweb/textimage_size] Typo3 13 version (Issue #4)

   Hello.
   Yes, I have integrated the library. I will download it again and test it. I will get back to you. But it will be around the afternoon.

**Comment by specialistaweb** [comment]
just published the new version 4,0.1, please tell me if it runs correctly. I modified some files/css and tried under TYPO3 12 (bs 14) and TYPO3 13 (bs15)

**Comment by gmt-it** [comment]
Hi.
I just tested it. It doesn't work. I think it's because the bootstrap package doesn't integrate the layout.
Take a look at: 
typo3-134/vendor/bk2k/bootstrap-package/Resources/Private/Layouts/ContentElements/Default.html

I think it would be easier to use TCEFORM.tt_content.frame_layout instead of TCEFORM.tt_content.layout, as this is taken into account. This is probably easier than adjusting the default.html. Only then you also have to adjust the BS FrameViewHelper.php.

**Comment by gmt-it** [comment]
I tried it out. The frame class is adopted but the size of the images remains unchanged. 
[textimage_size-main.zip](https://github.com/user-attachments/files/18010436/textimage_size-main.zip)

![image](https://github.com/user-attachments/assets/31742e82-238b-42d1-949d-b870b77bc918)

**Comment by specialistaweb** [comment]
hi

   please tell me your data

   * TYPO3 version

   * bootstrap package version

   so I can replicate exactly the same production environment

   before download the latest from repository textimage_size v. 4.0.1

   then try again and describe what happens

   thanx ddeesn and telMessage ID: ***@***.***>

**Comment by gmt-it** [comment]
Typo3 13.4.1 (ddev composer install)
bootstrap-package:  latest dev-master.

Tested 4.0.1 with same result.

**Comment by specialistaweb** [comment]
Hi see the following image, maybe as you stated, you are ussing a latest dev-master of bootstrap package.
I have installed the extensions below and for me all is working correctly
![screenshot](https://github.com/user-attachments/assets/1194f88e-ed41-46eb-91de-626d3c2d4844)

Site is running under PHP 8.2.26 and php8.2-fpm

**Comment by specialistaweb** [comment]
if you want, you can send me the credential to access your site.

   Write to ***@***.***

**Comment by gmt-it** [comment]
Hi.
Are you really sure? I have now installed the Bootstrap Package 15.0. The Bootstrap Package does not include Options Layout in the rendering! How can this work for you? Unfortunately I cannot give you access because the site runs locally under ddev and is not accessible from outside.

Here 6771 was set. It is definitely not included in the rendering. I don't understand why it works for you.
![image](https://github.com/user-attachments/assets/8e5cf717-349f-4074-91ae-51f0e68bb7b4)

**Comment by specialistaweb** [comment]
I enclose here two screenshot - first: inclusion of the library; second: options displayed within the layout menu. Try to clear all caches and moreover under the Maintanance menu > Clear cache
![textimage_includes](https://github.com/user-attachments/assets/c8eaeee5-6017-46a4-9e2e-37c9eb555307)
![textimage_options](https://github.com/user-attachments/assets/2f5dff06-b4a5-4971-a86a-d88d34182d30)

**Comment by specialistaweb** [comment]
and more see here:
![site_extensions](https://github.com/user-attachments/assets/6adbd348-ca08-488f-82d8-bf51d6e41a48)
![site_version](https://github.com/user-attachments/assets/9f4e09c5-81a8-471b-ba3b-4f5fcc218b2f)

**Comment by specialistaweb** [comment]
however if you cannot see any item within the layout menu of the content, go to your home page, modify the property and past the following code within the box "page ts config" within Resources tab:

###########
# TCEFORM #
###########


TCEFORM.tt_content.layout.disableNoMatchingValueElement = 0

TCEFORM.tt_content.layout.types.textpic {
  addItems.6761  = image/media size 8%
  addItems.6762  = image/media size 16%
  addItems.6763  = image/media size 25%
  addItems.6764  = image/media size 33%
  addItems.6765  = image/media size 41%
  addItems.6766  = image/media size 50%
  addItems.6767  = image/media size 58%
  addItems.6768  = image/media size 66%
  addItems.6769  = image/media size 75%
  addItems.6770  = image/media size 83%
  addItems.6771  = image/media size 91%
}

TCEFORM.tt_content.layout.types.textmedia {
  addItems.6761  = image/media size 8%
  addItems.6762  = image/media size 16%
  addItems.6763  = image/media size 25%
  addItems.6764  = image/media size 33%
  addItems.6765  = image/media size 41%
  addItems.6766  = image/media size 50%
  addItems.6767  = image/media size 58%
  addItems.6768  = image/media size 66%
  addItems.6769  = image/media size 75%
  addItems.6770  = image/media size 83%
  addItems.6771  = image/media size 91%
}

TCEFORM.tt_content.layout.types.image {
  addItems.6761  = image/media size 8%
  addItems.6762  = image/media size 16%
  addItems.6763  = image/media size 25%
  addItems.6764  = image/media size 33%
  addItems.6765  = image/media size 41%
  addItems.6766  = image/media size 50%
  addItems.6767  = image/media size 58%
  addItems.6768  = image/media size 66%
  addItems.6769  = image/media size 75%
  addItems.6770  = image/media size 83%
  addItems.6771  = image/media size 91%
}

**Comment by gmt-it** [comment]
Hi.
I think we're talking past each other. In the bootstrap file /vendor/bk2k/bootstrap-package/Resources/Private/Layouts/ContentElements/Default.html the layout setting is not taken into account and is not rendered by the bootstrap viewhelper. It doesn't matter what you set in the layout options! It is not taken into account. Of course I deleted all caches. I even installed a completely clean test environment yesterday. So just typo3 13.4.1, Bootstrap Package and your extension. Based on the bootstrap files alone, the layout option cannot and will not be used. It doesn't matter what I select in the options!
![image](https://github.com/user-attachments/assets/ae1f8d9b-c612-42f7-85c0-20399974e655)

**Comment by specialistaweb** [comment]
ok I have undestrand. My TYPO3 installation is a fresh installation with bootstrap package and shown in the images enclosed (post above).

   However I do not know why for me all is OK and  works without problems.

   Let me investigate and I hope to fix this annoying bug
   Thank you for you suggestion about the file Default.html

**Comment by gmt-it** [comment]
Hi.
I think this could be the solution:

[https://github.com/benjaminkott/bootstrap_package/pull/1268](https://github.com/benjaminkott/bootstrap_package/pull/1268)

[https://stackoverflow.com/questions/74789396/layout-classes-from-tceform-not-showing-in-bootstrap-package-frontend](https://stackoverflow.com/questions/74789396/layout-classes-from-tceform-not-showing-in-bootstrap-package-frontend)

**Comment by specialistaweb** [comment]
Hi if you see this page:

https://lab13.borgomodotto.it/#c3

you will notice that the layout data are displayed on the debug output, if you need to be inspired analize the data passed.
Expand data section, I found;

CType => 'textmedia' (9 chars)
categories => 0 (integer)
layout => 6764 (integer)

this data regards the text/media published below in the page

Output of  ... ext/textimage_size/Resources/Private/Templates/ContentElements/ TextmediaAbove.html

the code inserted:
<f:debug>{_all}</f:debug>

As debug runs only lauched from BE, If you need, please contact me in private so I send you the credentials then you can inspect the code directly. Here the debug output:

Extbase Variable Dump
array(15 items)
settings => array(13 items)
backendlayout => '2_columns' (9 chars)
data => array(103 items)
uid => 3 (integer)
pid => 1 (integer)
tstamp => 1733401574 (integer)
crdate => 1733303654 (integer)
deleted => 0 (integer)
hidden => 0 (integer)
starttime => 0 (integer)
endtime => 0 (integer)
fe_group => '' (0 chars)
sorting => 64 (integer)
rowDescription => '' (0 chars)
editlock => 0 (integer)
sys_language_uid => 0 (integer)
l18n_parent => 0 (integer)
l10n_source => 0 (integer)
l10n_state => NULL
l18n_diffsource => '{"CType":"","colPos":"","header":"","header_layout":"","header_class":"","he
 ader_position":"","date":"","header_link":"","subheader":"","subheader_class
 ":"","bodytext":"","assets":"","imageorient":"","imagecols":"","image_zoom":
 "","layout":"","frame_class":"","space_before_class":"","space_after_class":
 "","frame_layout":"","frame_options":"","background_color_class":"","backgro
 und_image":"","background_image_options":"","sectionIndex":"","linkToTop":""
 ,"categories":"","sys_language_uid":"","hidden":"","starttime":"","endtime":
 "","fe_group":"","editlock":"","rowDescription":""}' (583 chars)
t3ver_oid => 0 (integer)
t3ver_wsid => 0 (integer)
t3ver_state => 0 (integer)
t3ver_stage => 0 (integer)
frame_class => 'default' (7 chars)
colPos => 0 (integer)
table_caption => NULL
tx_impexp_origuid => 0 (integer)
**CType => 'textmedia' (9 chars)
categories => 0 (integer)
layout => 6764 (integer)**
space_before_class => 'medium' (6 chars)
space_after_class => '' (0 chars)
bullets_type => 0 (integer)
date => 0 (integer)
header => 'Header' (6 chars)
header_layout => 0 (integer)
header_position => '' (0 chars)
header_link => '' (0 chars)
subheader => '' (0 chars)
bodytext => '<p>Text Text Text Text Text Text Text Text Text Text Text Text Text Text Tex
 t Text Text Text Text Text Text Text Text T</p> <p>Text Text Text Text Text
  Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text
 Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text T
 ext Text Text Text Text Text Text Text Text Text Text Text Text Text Text Te
 xt Text Text Text Text Text Text&nbsp;</p>' (422 chars)
image => 1 (integer)
assets => 2 (integer)
imagewidth => 0 (integer)
imageheight => 0 (integer)
imageorient => 0 (integer)
imageborder => 0 (integer)
image_zoom => 0 (integer)
imagecols => 1 (integer)
cols => 0 (integer)
pages => NULL
recursive => 0 (integer)
list_type => '' (0 chars)
file_collections => NULL
media => 0 (integer)
filelink_size => 0 (integer)
filelink_sorting => '' (0 chars)
filelink_sorting_direction => '' (0 chars)
target => '' (0 chars)
records => NULL
sectionIndex => 1 (integer)
linkToTop => 0 (integer)
pi_flexform => NULL
selected_categories => NULL
category_field => '' (0 chars)
table_class => '' (0 chars)
table_delimiter => 124 (integer)
table_enclosure => 0 (integer)
table_header_position => 0 (integer)
table_tfoot => 0 (integer)
uploads_description => 0 (integer)
uploads_type => 0 (integer)
header_class => '' (0 chars)
subheader_class => '' (0 chars)
teaser => NULL
aspect_ratio => '1.3333333333333' (15 chars)
items_per_page => 10 (integer)
readmore_label => '' (0 chars)
quote_source => '' (0 chars)
quote_link => '' (0 chars)
panel_class => 'default' (7 chars)
file_folder => '' (0 chars)
icon => '' (0 chars)
icon_set => '' (0 chars)
icon_file => 0 (integer)
icon_position => '' (0 chars)
icon_size => 'default' (7 chars)
icon_type => 'default' (7 chars)
icon_color => '#FFFFFF' (7 chars)
icon_background => '#333333' (7 chars)
external_media_title => '' (0 chars)
external_media_source => '' (0 chars)
external_media_ratio => '' (0 chars)
tx_bootstrappackage_card_group_item => 0 (integer)
tx_bootstrappackage_carousel_item => 0 (integer)
tx_bootstrappackage_accordion_item => 0 (integer)
tx_bootstrappackage_icon_group_item => 0 (integer)
tx_bootstrappackage_tab_item => 0 (integer)
tx_bootstrappackage_timeline_item => 0 (integer)
frame_layout => 'default' (7 chars)
frame_options => '' (0 chars)
background_color_class => 'light' (5 chars)
background_image => 0 (integer)
background_image_options => array(4 items)
subitems_header_layout => 2 (integer)
tx_news_related_news => 0 (integer)
current => NULL
files => array(2 items)



backgroundImage => array(empty)
frameAttributes => array(empty)
variants => array(5 items)
backendlayoutConfig => array(5 items)
columnConfig => array(2 items)
columns => '12' (2 chars)
textimageinputsize => 4 (integer)
textimage-imagesize => 'col-md-4 m-auto' (15 chars)
textimage-style => 'textimage-size ' (15 chars)
imageConfig => array(1 item)

**Comment by gmt-it** [comment]
Hi.
You're great! It's ok that you see the layout in the debug, but please show me in the frontend where the layout is also set. This is the output of your test page. As you can see, the layout class is not set and is not taken into account. The previous two links that I posted to you show that this hasn't worked with the Bootstrap package since 2022. No matter what your debug says.

![image](https://github.com/user-attachments/assets/9196642a-deb9-4add-8394-f60fc909b50f)

According to the developers of the bootstrap package, this was done so that the responsive design would not be destroyed.
I had already tried to use what you inserted in the layout in the frame layout. The problem is that your CSS, even if the class is set, has no effect on the photos. Your extension will work with typo3 without the bootstrap package, but it cannot work with the package. So please show me your layout class set in frontend source.

**Comment by specialistaweb** [comment]
Forgive me, it is a bit difficult to understand, because when you talk about 'class' there is a bit of confusion (there is class of php, css class, etc.).

However textimage_size does not rely on or modify the Default.html file. Work only with the output and classes of the div containing the text and image or text and media content element, to maintain the positioning of the content according to the aspect field. 

Therefore what you report are classes that concern the div with frame that wraps all the content. If you see here: 
https://www.borgomodotto.it/il-borgo

this is the previous version of textimage_size 3.0.0 which runs under typo3 v.11.x and in this as in the others I have never overwritten the Default.html file. 

Therefore you point out these new styles that I have inserted, see image below if I'm not mistaken; If I can't replicate the behavior of your site, I have no idea how to proceed. If anything, explain the problem better: can't you align the images/media to the left or right or are all the contents always displayed in a single column?
![css_textmedia_above_screens](https://github.com/user-attachments/assets/621a9f82-f390-4aa9-a69e-913f08c841c0)

**Comment by specialistaweb** [comment]
Moreover I can give you the access as Admin to enter my site (test, online) and verify the extension installed, the bootstrap versionm, etc,, etc., infact  this is a test site and I can destroy and reconstruct as I want.

**Comment by specialistaweb** [comment]
A the end if you want modify CSS (SCSS styles) you can do it accessing to:
/var/www/<yoursite-address>/web/typo3conf/ext/textimage_size/Resources/Public/Scss/bootstrap5/textimage.scss

**Comment by gmt-it** [comment]
Works now! The problem was with my site set! My templates were always used and not those from the extension. Thank you for your patience!!

![image](https://github.com/user-attachments/assets/33ce029e-011c-4839-a888-867aa45e7a10)
